resources:
  pipelines:
  - pipeline: quizmeister-front
    source: quizmeister-front
   
trigger: 
  - master
   
stages:
  - stage: Deploy
    displayName: Deploy
    jobs:
      - deployment: DeployWeb
        variables: 
          production: true
          api: 'https://quizzes-api.quizmeister.net/'
          enableApplicationInsights: true
        pool: 
          vmImage: 'ubuntu-latest'
        environment: 'prd'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzurePowerShell@4
                displayName: Get instrumentationKey
                inputs:
                  azureSubscription: 'QuizmeisterAzureConnection'
                  scriptType: 'InlineScript'
                  Inline: |
                    Write-Host "Resource Group Name: quizmeister"
                    Write-Host "AppInsights Name: quizmeister-shared"
                    $instrumentationKey = (Get-AzApplicationInsights -ResourceGroupName "quizmeister" -Name "quizmeister-shared").InstrumentationKey
                    Write-Host "Instrumentation Key: $instrumentationKey"
                    Write-Host "##vso[task.setvariable variable=instrumentationKey;]$instrumentationKey"
                  azurePowerShellVersion: 'latestVersion'
                  pwsh: true
              - task: qetza.replacetokens.replacetokens-task.replacetokens@3
                displayName: 'Replace tokens'
                inputs:
                  targetFiles: '$(Pipeline.Workspace)/quizmeister-front/drop/**/env.js'
                  tokenPrefix: '#{'
                  tokenSuffix: '}#'
              - task: AzureResourceManagerTemplateDeployment@3
                displayName: 'Deploy client resources'
                inputs:
                  ConnectedServiceName: 'QuizmeisterAzureConnection'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'quizmeister'
                  location: 'West Europe'
                  csmFile: '$(Pipeline.Workspace)/quizmeister-front/drop/.azure-templates/quizmeisterClient.json'
                  deploymentMode: 'Incremental'
              - task: AzureRmWebAppDeployment@4
                displayName: 'Deploy client'
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'QuizmeisterAzureConnection'
                  appType: 'webAppLinux'
                  WebAppName: 'quizmeister-client'
                  package: '$(Pipeline.Workspace)/quizmeister-front/drop/dist/client'
              - task: AzureResourceManagerTemplateDeployment@3
                displayName: 'Deploy admin resources'
                inputs:
                  ConnectedServiceName: 'QuizmeisterAzureConnection'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'quizmeister'
                  location: 'West Europe'
                  csmFile: '$(Pipeline.Workspace)/quizmeister-front/drop/.azure-templates/quizmeisterAdmin.json'
                  deploymentMode: 'Incremental'
              - task: AzureRmWebAppDeployment@4
                displayName: 'Deploy admin'
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'QuizmeisterAzureConnection'
                  appType: 'webAppLinux'
                  WebAppName: 'quizmeister-admin'
                  package: '$(Pipeline.Workspace)/quizmeister-front/drop/dist/administration'
              - task: AzureResourceManagerTemplateDeployment@3
                displayName: 'Deploy presentation resources'
                inputs:
                  ConnectedServiceName: 'QuizmeisterAzureConnection'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'quizmeister'
                  location: 'West Europe'
                  csmFile: '$(Pipeline.Workspace)/quizmeister-front/drop/.azure-templates/quizmeisterPresentation.json'
                  deploymentMode: 'Incremental'
              - task: AzureRmWebAppDeployment@4
                displayName: 'Deploy presentation'
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'QuizmeisterAzureConnection'
                  appType: 'webAppLinux'
                  WebAppName: 'quizmeister-presentation'
                  package: '$(Pipeline.Workspace)/quizmeister-front/drop/dist/presentation'