trigger: none

stages:
- stage: 'build' 
  jobs:
  - job: 'build'
    pool: 
      vmImage: 'ubuntu-latest'
    steps:
      - task: NodeTool@0
        displayName: 'Get node'
        inputs:
          versionSpec: '12.x'
      - script: npm ci
        displayName: 'Install npm packages'
      - script: 'npm run build:admin'
        displayName: 'Build admininistration'
      - script: 'npm run build:client'
        displayName: 'Build client'
      - script: 'npm run build:present'
        displayName: 'Build presentation'
      - task: CopyFiles@2
        displayName: 'Copy build output'
        inputs:
          contents: 'dist/**'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: CopyFiles@2
        displayName: 'Copy arm template files'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '.azure-templates/**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - publish: $(Build.ArtifactStagingDirectory)
        displayName: 'Publish artifacts'
        artifact: 'drop'