trigger:
  branches:
    include:
    - master
  paths:
    include:
    - resource-group/*
    - networking/*
    - certificate-domain-templates/*
    - database/*
    - signalr/*
    exclude:
    - README.md

variables:
    location: 'West Europe'
    artifactName: 'templates'

stages:

- stage: Publish
  displayName: Publish

  jobs:
    - job: PublishdJob
      displayName: Copy and Publish Artifacts
      pool:
        vmImage: 'windows-latest'

      steps:
        - task: CopyFiles@2
          displayName: Copy files
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - publish: $(Build.ArtifactStagingDirectory)
          displayName: 'Publish build artifacts'
          artifact: '$(artifactName)'
    
- stage: DeployResources
  displayName: Deploy certificates, domains and database
  dependsOn: Publish

  jobs:
  - deployment: DeploymentJob
    displayName: Deploy certificates, domains and database 
    pool:
      vmImage: 'windows-latest'
    environment: 'shared'
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: '$(artifactName)'
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Create resource group
              inputs:
                deploymentScope: 'Subscription'
                ConnectedServiceName: 'QuizmeisterAzureConnection'
                subscriptionName: 'ab29d196-b8bf-4152-836c-be99f78f6748'
                location: $(location)
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)\$(artifactName)\resource-group\azuredeploy.json'
                csmParametersFile: '$(Pipeline.Workspace)\$(artifactName)\resource-group\azuredeploy-resources.parameters.json'
                deploymentMode: 'Incremental'
                deploymentOutputs: 'armOutputs'

            - task: AzurePowerShell@4
              displayName: Get resource group name
              inputs:
                azureSubscription: 'QuizmeisterAzureConnection'
                scriptType: 'InlineScript'
                Inline: |
                  $var=ConvertFrom-Json '$(armOutputs)'
                  $value=$var.resourceGroupName.value
                  Write-Host "##vso[task.setvariable variable=resourceGroupName;]$value"
                azurePowerShellVersion: 'latestVersion'
                pwsh: true

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Deploy network
              inputs:
                deploymentScope: 'Resource Group'
                ConnectedServiceName: 'QuizmeisterAzureConnection'
                subscriptionName: 'ab29d196-b8bf-4152-836c-be99f78f6748'
                action: 'Create Or Update Resource Group'
                resourceGroupName: '$(resourceGroupName)'
                location: $(location)
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)\$(artifactName)\networking\network.json'
                csmParametersFile: '$(Pipeline.Workspace)\$(artifactName)\networking\network.parameters.json'
                deploymentMode: 'Incremental'
                deploymentOutputs: 'armOutputs'
  
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Deploy certificate-domain-templates
              inputs:
                deploymentScope: 'Resource Group'
                ConnectedServiceName: 'QuizmeisterAzureConnection'
                subscriptionName: 'ab29d196-b8bf-4152-836c-be99f78f6748'
                action: 'Create Or Update Resource Group'
                resourceGroupName: '$(resourceGroupName)'
                location: $(location)
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)\$(artifactName)\certificate-domain-templates\certificatesAndDomain.json'
                csmParametersFile: '$(Pipeline.Workspace)\$(artifactName)\certificate-domain-templates\certificatesAndDomain.parameters.json'
                deploymentMode: 'Incremental'
                deploymentOutputs: 'armOutputs'

            - task: AzureKeyVault@1
              displayName: Get secrets
              inputs:
                azureSubscription: 'QuizmeisterAzureConnection'
                keyVaultName: quizmeister-vault
                secretsFilter: '*'

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Deploy database
              inputs:
                deploymentScope: 'Resource Group'
                ConnectedServiceName: 'QuizmeisterAzureConnection'
                subscriptionName: 'ab29d196-b8bf-4152-836c-be99f78f6748'
                action: 'Create Or Update Resource Group'
                resourceGroupName: '$(resourceGroupName)'
                location: $(location)
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)\$(artifactName)\database\database.json'
                csmParametersFile: '$(Pipeline.Workspace)\$(artifactName)\database\database.parameters.json'
                deploymentMode: 'Incremental'
                deploymentOutputs: 'armOutputs'
                overrideParameters: '-sqlAdministratorLogin "sqladmin" -sqlAdministratorPassword $(sqlAdministratorPassword)'
                

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Deploy signalR
              inputs:
                deploymentScope: 'Resource Group'
                ConnectedServiceName: 'QuizmeisterAzureConnection'
                subscriptionName: 'ab29d196-b8bf-4152-836c-be99f78f6748'
                action: 'Create Or Update Resource Group'
                resourceGroupName: '$(resourceGroupName)'
                location: $(location)
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)\$(artifactName)\signalr\signalr.json'
                deploymentMode: 'Incremental'
                deploymentOutputs: 'armOutputs'