resources:
  pipelines:
  - pipeline: quizmeister-azure-resources
    source: quizmeister-azure-resources

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - resource-group/*
    - storage-account-for-local-functions/*
    - storage-account-for-artifacts/*
    - linked-templates/*
    - main-template/*
    exclude:
    - README.md

variables:
    location: 'West Europe'
    artifactName: 'templates'

stages:

- stage: Publish
  displayName: Publish

  jobs:
    - job: PublishdJob
      displayName: Copy and Publish Artifacts
      pool:
        vmImage: 'windows-latest'

      steps:
        - task: CopyFiles@2
          displayName: Copy files
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - publish: $(Build.ArtifactStagingDirectory)
          displayName: 'Publish build artifacts'
          artifact: '$(artifactName)'
    
- stage: DeployToEnvironment
  displayName: Deploy to prd
  dependsOn: Publish

  jobs:
  - deployment: DeploymentJob
    displayName: Deploy to prd
    pool:
      vmImage: 'windows-latest'
    environment: 'prd'
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: '$(artifactName)'
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Create resource group
              inputs:
                deploymentScope: 'Subscription'
                ConnectedServiceName: 'QuizmeisterAzureConnection'
                subscriptionName: 'ab29d196-b8bf-4152-836c-be99f78f6748'
                location: $(location)
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)\$(artifactName)\resource-group\azuredeploy.json'
                csmParametersFile: '$(Pipeline.Workspace)\$(artifactName)\resource-group\azuredeploy-prd.parameters.json'
                deploymentMode: 'Incremental'
                deploymentOutputs: 'armOutputs'

            - task: AzurePowerShell@4
              displayName: Get resource group name
              inputs:
                azureSubscription: 'QuizmeisterAzureConnection'
                scriptType: 'InlineScript'
                Inline: |
                  $var=ConvertFrom-Json '$(armOutputs)'
                  $value=$var.resourceGroupName.value
                  Write-Host "##vso[task.setvariable variable=resourceGroupName;]$value"
                azurePowerShellVersion: 'latestVersion'
                pwsh: true

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Create a storage account for local functions
              inputs:
                deploymentScope: 'Resource Group'
                ConnectedServiceName: 'QuizmeisterAzureConnection'
                subscriptionName: 'ab29d196-b8bf-4152-836c-be99f78f6748'
                action: 'Create Or Update Resource Group'
                resourceGroupName: '$(resourceGroupName)'
                location: $(location)
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)\$(artifactName)\storage-account-for-local-functions\azuredeploy.json'
                csmParametersFile: '$(Pipeline.Workspace)\$(artifactName)\storage-account-for-local-functions\azuredeploy.parameters.json'
                deploymentMode: 'Incremental'
                deploymentOutputs: 'armOutputs'

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Create a storage account for deployment artifacts (PRD)
              inputs:
                deploymentScope: 'Resource Group'
                ConnectedServiceName: 'QuizmeisterAzureConnection'
                subscriptionName: 'ab29d196-b8bf-4152-836c-be99f78f6748'
                action: 'Create Or Update Resource Group'
                resourceGroupName: '$(resourceGroupName)'
                location: $(location)
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)\$(artifactName)\storage-account-for-artifacts\azuredeploy.json'
                csmParametersFile: '$(Pipeline.Workspace)\$(artifactName)\storage-account-for-artifacts\azuredeploy.parameters.json'
                deploymentMode: 'Incremental'
                deploymentOutputs: 'armOutputs'
  
            - task: AzurePowerShell@4
              displayName: Get the storage account and its container names (PRD)
              inputs:
                azureSubscription: 'QuizmeisterAzureConnection'
                scriptType: 'InlineScript'
                Inline: |
                  $var=ConvertFrom-Json '$(armOutputs)'
                  $value=$var.storageAccountName.value
                  Write-Host "##vso[task.setvariable variable=storageAccountName;]$value"
                  $value=$var.storageContainerName.value
                  Write-Host "##vso[task.setvariable variable=storageContainerName;]$value"
                azurePowerShellVersion: 'latestVersion'
                pwsh: true
    
            - task: AzureFileCopy@3
              displayName: Copy deployment artifacts to the storage account (PRD)
              inputs:
                sourcePath: '$(Pipeline.Workspace)\$(artifactName)\linked-templates'
                azureSubscription: 'QuizmeisterAzureConnection'
                destination: azureBlob
                storage: $(storageAccountName)
                containerName: $(storageContainerName)
                blobPrefix: 'linked-templates'
                cleanTargetBeforeCopy: true
                outputStorageUri: artifactsLocation
                outputStorageContainerSasToken: artifactsLocationSasToken
                sasTokenTimeOutInMinutes: 30
      
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Validate deploy
              inputs:
                deploymentScope: 'Resource Group'
                ConnectedServiceName: 'QuizmeisterAzureConnection'
                subscriptionName: 'ab29d196-b8bf-4152-836c-be99f78f6748'
                action: 'Create Or Update Resource Group'
                resourceGroupName: '$(resourceGroupName)'
                location: $(location)
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)\$(artifactName)\main-template\azuredeploy.json'
                csmParametersFile: '$(Pipeline.Workspace)\$(artifactName)\main-template\azuredeploy.parameters.json'
                overrideParameters: '-_artifactsLocation $(artifactsLocation) -_artifactsLocationSasToken $(artifactsLocationSasToken)'
                deploymentMode: 'Validation'
                deploymentOutputs: 'armOutputs'

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Deploy resources
              inputs:
                deploymentScope: 'Resource Group'
                ConnectedServiceName: 'QuizmeisterAzureConnection'
                subscriptionName: 'ab29d196-b8bf-4152-836c-be99f78f6748'
                action: 'Create Or Update Resource Group'
                resourceGroupName: '$(resourceGroupName)'
                location: $(location)
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)\$(artifactName)\main-template\azuredeploy.json'
                csmParametersFile: '$(Pipeline.Workspace)\$(artifactName)\main-template\azuredeploy.parameters.json'
                overrideParameters: '-_artifactsLocation $(artifactsLocation) -_artifactsLocationSasToken $(artifactsLocationSasToken)'
                deploymentMode: 'Incremental'
                deploymentOutputs: 'armOutputs'            