resources:
  pipelines:
  - pipeline: quizmeister-api
    source: quizmeister-api

trigger: 
  - master

stages: 
  - stage: DeployToPRD
    displayName: Deploy to prd
    jobs:
      - deployment: DeployWeb
        pool: 
          vmImage: 'ubuntu-latest'
        environment: 'prd'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: UseDotNet@2 
                displayName: ".NET 5.0.x"
                inputs:
                  version: '5.0.x'
                  packageType: sdk
              
              - task: ExtractFiles@1
                inputs:
                  archiveFilePatterns: '$(Pipeline.Workspace)/quizmeister-api/drop/Api/*.zip' 
                  destinationFolder: '$(Pipeline.Workspace)/quizmeister-api/replacetokens'
                  cleanDestinationFolder: true 

              - task: AzureKeyVault@1
                inputs:
                  azureSubscription: 'QuizmeisterAzureConnection'
                  keyVaultName: 'quizmeister-vault'
                  secretsFilter: '*'

              - task: qetza.replacetokens.replacetokens-task.replacetokens@3
                displayName: 'Replace tokens'
                inputs:
                  targetFiles: '$(Pipeline.Workspace)/quizmeister-api/**/*.json'
                  tokenPrefix: '#{'
                  tokenSuffix: '}#'

              - task: PowerShell@2
                displayName: 'Migrations'
                inputs:
                  targetType: 'inline'
                  script: 'dotnet MigrationTool.dll'
                  workingDirectory: $(Pipeline.Workspace)/quizmeister-api/drop/MigrationTool

              - task: ArchiveFiles@2
                inputs:
                  rootFolderOrFile: '$(Pipeline.Workspace)/quizmeister-api/replacetokens' 
                  archiveFile: '$(Pipeline.Workspace)/deploy/drop.zip'
                  includeRootFolder: false
                  archiveType: 'zip'

              - task: AzureResourceManagerTemplateDeployment@3
                displayName: 'Deploy api resources'
                inputs:
                  ConnectedServiceName: 'QuizmeisterAzureConnection'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'quizmeister'
                  location: 'West Europe'
                  csmFile: '$(Pipeline.Workspace)/quizmeister-api/drop/.azure-templates/quizmeisterQuizzesApi.json'
                  deploymentMode: 'Incremental'

              - task: AzureRmWebAppDeployment@4
                displayName: 'Deploy webApp'
                inputs:
                  azureSubscription: 'QuizmeisterAzureConnection'
                  appType: 'webAppLinux'
                  WebAppName: 'quizmeister-quizzes-api'
                  packageForLinux: '$(Pipeline.Workspace)/deploy/drop.zip'
                  RuntimeStack: 'DOTNETCORE|5.0'
                  StartupCommand: 'QuizmeisterApi'
