trigger: none

stages:
  - stage: build
    jobs:
    - job: build
      pool: 
        vmImage: 'ubuntu-latest'
      steps:
        - task: UseDotNet@2 
          displayName: ".NET 5.0.x"
          inputs:
            version: '5.0.x'
            packageType: sdk
        
        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: 'build'
            arguments: '--configuration $(buildConfiguration)'
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: Publish Api
          inputs:
            command: 'publish'
            publishWebProjects: true
            workingDirectory: Api/
            arguments: '--configuration Release --self-contained true --runtime linux-x64 --output $(Build.ArtifactStagingDirectory)/Api'
            projects: '**/QuizmeisterApi.csproj'

        - task: DotNetCoreCLI@2
          displayName: Build migration tool
          inputs:
            command: build
            workingDirectory: MigrationTool/
            projects: '**/MigrationTool.csproj'
            arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/MigrationTool'

        - task: CopyFiles@2
          displayName: 'Copy arm template files'
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: '.azure-templates/**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
            
        - task: PublishBuildArtifacts@1
          displayName: "Upload Artifacts"
          inputs:
            pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
            artifactName: 'drop' 
